### ISSUE TITLE
[react-query] Bugs & improvements

### ISSUE THREAD

**Issue by TwistedMinda** [pmndrs/jotai#1210]
Hello!

Creating this issue as a clean & centralized document for problems related to react-query, without the need of reading through all the issues titles. The intention is to find someone that knows RQ well to tackle some or all of these remaining issues:

- [x] [Prevent suspend with keepPreviousData](https://github.com/pmndrs/jotai/issues/957) **(bug)**

- [x] [Mutations support, atomWithMutation](https://github.com/pmndrs/jotai/issues/309) (enhancement) 

- [x] [Seperate atom with infinite query status](https://github.com/pmndrs/jotai/issues/1068) (enhancement)

- [x] [Usage with devtools](https://github.com/pmndrs/jotai/issues/1105) (documentation)

- [x] [Reset after an error](https://github.com/pmndrs/jotai/issues/1129) (enhancement)

- [x] [Recovering from an error](https://github.com/pmndrs/jotai/issues/1199) (enhancement)
  - remaining warning when using `loadable` API
  - remaining error + warning when using `ErrorBoundary` API

- [x] [Preact state problem](https://github.com/pmndrs/jotai/issues/570) (bug)

**Comment by milutinovici** [comment]
Also doesn't seem to be working with [persistQueryClient](https://tanstack.com/query/v4/docs/plugins/persistQueryClient)

**Comment by dai-shi** [comment]
Have you tried it? We could only use non-React functions. Maybe we need a doc for it. Can you help?

**Comment by milutinovici** [comment]
I have tried it. In react-query, you wrap your components with

```
  <PersistQueryClientProvider
    client={queryClient}
    persistOptions={{ persister }}
  >
    <App />
  </PersistQueryClientProvider>
```
I'm guessing Jotai doesn't do that, but I haven't looked and the source of either libs.

Currently I'm swamped, maybe in the future?

**Comment by dai-shi** [comment]
I think we want to start with a simple one:
```js
// 🚨 never unsubscribes from syncing
persistQueryClient({
  queryClient,
  persister: localStoragePersister,
})
```
If it works as expected, then the next step is how to unsubscribe. (and there would be several approaches.)

**Comment by dai-shi** [comment]
cc: @Aslemammad If you have time, can you try creating a codesandbox example?

**Comment by milutinovici** [comment]
Here you go my man [CodeSandbox](https://codesandbox.io/s/jotai-persisted-react-query-oj38rk)

First time it renders, it fires both requests, on all subsequent renders, it fires only the jotai one. Clearing the localStorage fires both again.

**Comment by dai-shi** [comment]
You are not using `persistQueryClient`, which is necessary for jotai because `PersistQueryClientProvider` doesn't work.
Here you go: https://codesandbox.io/s/jotai-persisted-react-query-forked-iwd7cb

> If it works as expected, then the next step is how to unsubscribe. (and there would be several approaches.)

So, the next is the next step.

**Comment by dai-shi** [comment]
All done.
