### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#333]
We are getting ready. Here's action items.

## Fixing bugs

For this we need more bug reports.

- [x] #327 Snowpack atomState.d is not defined
- [x] #351 Freezes when updating multiple async atoms
- [x]  #354 'The path "." is not exported by "jotai"' using esbuild
- [x] #355 `setAtom` doesn't bail on same value if component reads from another atom
- [x] #373 "Too many re-renders."
- [x] #375 value from atom is not update and component is not rendered
- [x] #389 Write function with delayed call to set
- [x] #398 `useAtomCallback` doesn't have types for 3-param signature
- [x] #434 async read atoms keep waiting the first promise to be resolved and can't be overriden by the second promise @dai-shi
- [x] (#433) Improve `atom()` typing #438
- [x] #442 Resolution of Promise atoms does not propagate correctly. @dai-shi 
- [x] #443 Endless API call with 0.16.2, strange behavior @dai-shi @Aslemammad 
- [x] #476 Bad setState() call when use atomWithQuery
- [x] #490 [BUG] derived atoms don't update depended on other atoms which update when router back
- [x] #491 [useAtomCallback] Incorrect return type 
- [x] #492 [BUG] TypeError: source[GET_VERSION] is not a function
- [x] (#500) atomWithQuery with `enabled` option doesn't work on remount @dai-shi @Aslemammad 
- [x] #512 atomFamily not updating with param from another atom
- [x] #517 [Bug] atom state not found in flush undefined (introduced in 0.16.11) #518 

## Improving docs

This is most important for v1.

- [x] #335 [Docs] add provider-less mode
- [x] #319 Docs: Intro with conceptual differences with Redux, Context API, etc.
- [x] #401 [Docs] Improve Getting Started
- [x] #402 [Docs] Improve introduction to async
- [x] #429 [Docs] Rewrite persistence guide @dai-shi
- [x] #435 [Docs] How to deal with atoms in atom guide @dai-shi 
- [x] #255 [Question] Best practices for large objects?
- [x] #269 [Question] Can jotai be used without Suspense?
- [x] #436 [Docs] Improve atomFamily typings to be obvious to use
- [x] #252 [Question] How do you unit test Jotai atoms?
- [x] demo website @sandren #519 

## Improving types and tests

- [x] fix: export some types and hide some internal types #488
- [x] #337 Add TS Except tests for v1 @Thisen 

## Improving apis

- [x] feat(util): atomWithDefault #379
- [x] Feature: waitFor utilities #358
- [x] #385 Generalize atomFamily (BREAKING CHANGE)
- [x] feat(util): atomWithStorage #394 @sandren 
- [x] feat(util): atomWithHash #407 @dai-shi
- [x] #430 Support primitive atoms with a Promise as the initial value. @dai-shi 
- [x] feat(utils): add `freezeAtomCreator`, drop `atomFrozenInDev` (BREAKING CHANGE) #441 @dai-shi
- [x] #231 Focus Atoms with async atoms?
- [x] #452 extend atomWithImmer to accept normal update

## Benchmarking

- [x] js-framework-benchmark @Thisen 
- [x] #245 Performance measurement #486 @dai-shi 
- [x] Benchmark tool: porting `react-redux-benchmarks` @Aslemammad https://github.com/Aslemammad/react-state-benchmarks

## Devtools

We have `useDebugState` in Provider and `jotai/devtools` for Redux DevTools Ext.

It would be nice to have a dedicated devtools.

- [x] #388 Snapshot-based devtools @Thisen 

## Adding features

This is actually not required for v1, but nice to have.

- [x] jotai/valtio #405 
- [x] jotai/zustand #419 
- [x] jotai/redux #421 
- jotai/rxjs #341
- #427 Create a bindings to the URQL GraphQL Client. #463 @dai-shi 
- #309 [jotai/query] atomWithMutation @aulneau 
- [jotai/xstate] atomWithService, atomWithActor (maybe after v1)
- useAtomCallback for async @Thisen (from ideating)

## Tutorials

Maybe we should do this outside repo.
Anyone would like to write blog posts or something?

## Release Note

- [x] Prepare release note draft

<details>
<summary>Draft</summary>

# Announcing Jotai v1

![preview](https://jotai.pmnd.rs/preview_DRAFT.png)

We are pleased to announce jotai v1 release!
Jotai is a primitive and flexible state management library for React.

Demos:
- [Text Length example](https://githubbox.com/pmndrs/jotai/tree/master/examples/text_length)
- [Hacker News example](https://githubbox.com/pmndrs/jotai/tree/master/examples/hacker_news)
- [Todos example](https://githubbox.com/pmndrs/jotai/tree/master/examples/todos)

## Global state like useState

Jotai's atoms can be used like useState, but it's global state.

```tsx
const yearAtom = atom(2021)

const Component = () => {
  const [year, setYear] = useAtom(yearAtom)
  return <>{year} <button onClick={() => setYear((c) => c + 1)}>Next</button>
}
```

## Derived state

You can create a derived atom with `read` function.

```tsx
const meterAtom = atom(1000)
const kilometerAtom = atom((get) => get(meterAtom) / 1000)
```

## Minimal API and additional utilities

Jotai core `jotai` exposes only two functions `atom`, `useAtom` and one optional component `Provider`.

We have more functions in separate bundles `jotai/*`, such as `jotai/utils` and `jotai/devtools`.
For example, those include `atomWithStorage`, `atomWithReset`, `atomFamily`, to name a few.
They are all implemented with the public api of jotai core.
So, you can also create a similar third-party library.

## Async support

Jotai comes with Suspense support. If your `read` function is async, it will suspend behind the scenes, and you wouldn't need to care async state in your code.

```jsx
const idAtom = atom('id001')
const dataAtom = atom(async (get) => {
  const response = await fetch(`.../${id}`)
  return response.json()
}

const Component = () => {
  const [data] = useAtom(dataAtom)
  return <>{data.title} - {data.author}</>
}
```

### Notes about Suspense

We use the undocumented behavior of "Suspense for Lazy Loading" for any async.
"Suspense for Data Fetching" is still to be finalized.
Hence, this feature is technically unstable. We try our best to keep the API when it migrates.

## Integrations

Jotai comes with various integrations. Some of them are complete, some are preliminary.

  - `jotai/immer`: [immer](https://github.com/immerjs/immer) integration
  - `jotai/optics`: [optics-ts](https://github.com/akheron/optics-ts) integration
  - `jotai/query`: [react-query](https://github.com/tannerlinsley/react-query) integration
  - `jotai/xstate`: [xstate](https://github.com/davidkpiano/xstate) integration
  - `jotai/valtio`: [valtio](https://github.com/pmndrs/valtio) integration
  - `jotai/zustand`: [zustand](https://github.com/pmndrs/zustand) integration
  - `jotai/redux`: [redux](https://github.com/reduxjs/redux) integration

## Moving forward

The core API should be stable for React 16.8 and above.
All major issues are resolved, and if there is a bug by chance, we will fix it as soon as possible.

We will be adding more utility functions on top of core, and your use cases would be important. Free free to open a [new discussion](https://github.com/pmndrs/jotai/discussions/new).

We are already working on new integrations for [urql](https://github.com/FormidableLabs/urql) and [rxjs](https://github.com/ReactiveX/rxjs). We have a plan to work on dedicated integration for [nextjs](https://github.com/vercel/next.js/).

When React releases a new version with Suspense and Concurrent support, we will start working on the next major version. Our hope is to keep the API compatible.

### Notes about Versioning

We follow semantic versioning for core `jotai`.
Note that type-only changes and sub bundles `jotai/*` don't strictly follow the semver.
Please check release notes for details.

</details>

**Comment by Thisen** [comment]
I think basic devtools should be a part of v1. Then we will know that the snapshot parts are stable.

**Comment by Aslemammad** [comment]
@Aslemammad, I think I'm gonna do some about blog posts. But I have to finish some stuff going on here.

**Comment by RIP21** [comment]
If some will wrap `urql` client into `jotai` it will be awesome :) But I guess it will require some good knowledge of internals to make it right.
This thingy :)
https://github.com/FormidableLabs/urql

**Comment by dai-shi** [comment]
@RIP21 Nice idea. Would you create a dedicated issue please? I'm interested, but if someone is too, they can try.

**Comment by RIP21** [comment]
@dai-shi done https://github.com/pmndrs/jotai/issues/427 :)
BTW, thanks for your work! :) Love Jotai so far :)

**Comment by dai-shi** [comment]
We did it! 🎉 🎉 🎉
